Feature 5
apmath-web/credit-kotlin pull request #13
Opened 2018-12-04 11:05 UTC by BarracudaPff

- [x] создать класс `Payment`
- [ ] создать связь с классом `Credit`

2018-12-04 11:06 UTC, BarracudaPff commented
Что-то странное с платежами, если в классе лежат только входные данные из платежа (см. осуществление платежа по кредиту), то как тогда должен работать viewModels.Payment.hydrate, когда все данные лежат в valueObjects.Payment.hydrate
И зачем нужен viewModels.Payment.fetchJson, когда это эти данные не нужно кидать в JSON, только считывать. Мне кажется или тут что-то напутано?

2018-12-05 18:30 UTC, malinink commented
@BarracudaPff Погодите, не спешите, давайте по порядку.
Все методы сразу в одном экшене не нужны, они будут использоваться в разных экшенах. Гдето-то мы получает платеж, а гдето его возвращаем.
Давате более конкретный вопрос, и я уже на него отвечу.

2018-12-05 18:51 UTC, BarracudaPff commented
Окей, давайте сначала про метод `viewModels.Payment.hydrate(...)`.
В методе мы принимаем `(payment : valueObjects.PaymentInterface)` и хотим заполнить поля класса исходя из `payment`. Разве не наоборот?
Когда приходит `PUT-запрос`, мы создаем объект `viewModels.Payment`, а из него создаем объект `valueObjects.Payment`. Метод `hydrate(...)` из `viewModels.Payment` работает наоборот.

2018-12-05 19:03 UTC, malinink commented
Нет, не наоборот, метод `hydrate` нужен для отображение `VO` во `VM` с целью в дальнейшем получить JSON
Когда мы получаем запрос, на погашение, мы получаем в итоге  `VO` из которого получим все необходимые составные части и в экшене передадим их в конструктор

2018-12-05 19:08 UTC, BarracudaPff commented
Можно уточнить, когда вызывается метод `PUT-запроса` на погашение платежа, должен создаваться `VO`?

2018-12-05 19:09 UTC, BarracudaPff commented
Просто зачем тогда `VM` переводить в JSON, мы же нигде не возвращаем JSON c такими данными.

2018-12-06 10:44 UTC, malinink commented
Как, а метод получения списка платежей?

2018-12-08 07:45 UTC, malinink requested changes

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/ViewModel.kt
> +        const val MESSAGE_STATE_UNKNOWN         = "Must be a valid currency ['PAID', 'UPCOMING'] allowed"
`state` а не `currency`
Также у меня предложение эти константы вынести в payment VM т.к. они на данный момент только там и используются.

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +}
EOF

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        const val PAYMENT = "currency"
используйте тябуляцию, так будет намного информативнее

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +    override fun fetchJson(): JSONObject {
Маловато свойств
Должны быть все, что по спецификации: https://docs.google.com/document/d/1jJT-Vsn8LIrJiOjc5IwOjfP7wIftqV6yCc_uAKWMC_E/edit#heading=h.csw3mksjckq4

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +            currency = Currency.valueOf(raw)
что за магия? Уверены что это работает? Я - нет.

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        return loadAndValidatePayment(json)
опять же, не будет работать как надо, выйдет на первом false,

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        this.payment = payment.payment
тут аналогично `fetch` должно быть больше параметров

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +    override val validation: ValidationInterface = Validation()
лишнее, в базовом классе сделано

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +class Payment(
напишите для бдительности тест, аналогичный `Credit`. Большой класс, мне кажется не повередит.

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +        payments.add(payment)
TODO оставьте, добавление платежа - это лишь последний шаг, необходимо ещё всю логику проверок тут будет добавить.

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/domain/data/Type.kt
>  }
EOF

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/domain/data/State.kt
>  }
EOF

2018-12-08 07:45 UTC, malinink commented on src/main/kotlin/domain/data/Money.kt
> -inline class Money(val value: Long)
Не согласен, верните назад. Используйте число как число, нам строка не нужна.

2018-12-08 07:45 UTC, malinink commented on build.gradle
> +    kotlinOptions {
что это дает?
Используйте последний котлин, проблем не будет.
А конструкцию можно убрать.

2018-12-11 05:37 UTC, BarracudaPff commented on src/main/kotlin/viewModels/Payment.kt
> +            currency = Currency.valueOf(raw)
Да, работать будет, плюс тесты проходит.

2018-12-11 05:39 UTC, BarracudaPff commented on src/main/kotlin/viewModels/Payment.kt
> +        return loadAndValidatePayment(json)
Нет, в Котлине это не тоже самое что &&. Будут выполнятся все методы, которые прописаны через .and(). Сделал немного тестов по loadAndValidation

2018-12-11 05:41 UTC, BarracudaPff commented on src/main/kotlin/viewModels/Payment.kt
> +class Payment(
Пока что потенциально может идти не по плану только метод loadAndValidation, сделал немного тестов.

2018-12-11 05:52 UTC, BarracudaPff commented on src/main/kotlin/viewModels/Payment.kt
> +    override fun fetchJson(): JSONObject {
Так в этом у меня и была проблема, например, откдука/куда класть body, percent, fullEarlyRepayment. Они все лежат VO Payment'е

2018-12-11 14:54 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +    override fun fetchJson(): JSONObject {
добавьте полей соответствующих

2018-12-11 15:01 UTC, malinink requested changes

2018-12-11 15:01 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        return loadAndValidatePayment(json)
Прикольно, погляжу.

2018-12-11 15:01 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        if (long < 1 || long > 3000000000000000) {
немного изменилась спецификация по значению этого поля, подправьте.

2018-12-11 15:01 UTC, malinink commented on src/test/kotlin/viewModels/PaymentValidationTest.kt
> +}
EOF

2018-12-11 15:01 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +    private fun loadAndValidateCurrency(json: JSONObject): Boolean {
поглядите спецификацию, много полей не обязательных, или имеют дефолтные знчения, предлагаю их тут и устанавливать сразу же.

2018-12-11 15:01 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        raw.toUpperCase()
лишнее, + не факт что нам надо валидировать корректно "currency": "usd", во всяком случае наша спецификация предполагает что это не корректный формат, поэтому предлагаю брать измнение пользовательских данных.

2018-12-11 16:09 UTC, BarracudaPff commented
Вроде бы все подфиксил и еще добавил парочку тестов.

2018-12-11 18:53 UTC, malinink requested changes

2018-12-11 18:53 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        if (!json.has(TYPE)) {
E нас в ряде случаев, есть значения по-умолчанию, которые можно понять не по бизнес правилам.
Это, например, тип платежа.
Если же мы этот функцонал будем решать отдельно, то гораздо более красивым решением будет добавление отдельного метода,          `val raw = loadNullableNotRequiredField(json, TYPE) ?: return true`
И  использование его как в Сredit  VM так и тут.

2018-12-11 18:53 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +            addMessage(Message(PAYMENT, PAYMENT_BORDERS))
Во-первых, я уже задал правило, чтобы сообщения занывались `MESSAGE_*`
Во-вторых, не имеет большого сымысла выводить сообщение в константу, если оно используется единожды.

2018-12-11 18:57 UTC, malinink commented on src/test/kotlin/viewModels/PaymentValidationTest.kt
> +    fun paymentTrueValidation() {
использовали бы источник данных для тестов, и сделали бы тест для успешной валидации и не успешной.
как для средита сделано, гораздо удобнее добавлить новых тестов.

2018-12-12 07:45 UTC, malinink commented
@BarracudaPff Я ещё вечером сам зарефакторю, мы дольше туда-сюда будем кидать.

2018-12-12 09:32 UTC, BarracudaPff commented
👌

2018-12-12 19:56 UTC, malinink commented
@BarracudaPff предлагаю посмотреть мои изменения и фиксы, особенно в этом коммите: eba7eb1c36552778cb6d177e4c6165aa2e992b6f

2018-12-12 20:03 UTC, malinink submitted a review, later dismissed

2018-12-12 21:10 UTC, BarracudaPff commented
@malinink 
А вы точно не хотите сделать `loadField()` приватным и разбить его на подметоды?
Например:
```kotlin
protected fun loadFieldWithoutMessage(json: JSONObject, field: String): Any? {
    return loadField(json, field, false, false)
}
```
(название от балды)

2018-12-12 22:19 UTC, levkovalenko requested changes

2018-12-12 22:19 UTC, levozavr commented on src/main/kotlin/viewModels/Payment.kt
> +        remainCreditBody = payment.remainCreditBody
У нас по спецификации вроде идет так, что это поле добавляется только для платежей с определенным state.
![image](https://user-images.githubusercontent.com/30433199/49902290-98526c00-fe74-11e8-826f-088260ce1bf2.png)

2018-12-12 22:19 UTC, levozavr commented on src/main/kotlin/viewModels/Payment.kt
> +            .put(FULL_EARLY_REPAYMENT, fullEarlyRepayment?.value)
аналогичная ситуация, это поле появляется только при определенном state.
https://docs.google.com/document/d/1jJT-Vsn8LIrJiOjc5IwOjfP7wIftqV6yCc_uAKWMC_E/edit#heading=h.csw3mksjckq4

2018-12-12 22:41 UTC, BarracudaPff commented on src/main/kotlin/viewModels/Payment.kt
> +        remainCreditBody = payment.remainCreditBody
После небольших обсуждений, поняли что это поле вообще не нужно.

2018-12-13 06:05 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        remainCreditBody = payment.remainCreditBody
А по-моему нужно

2018-12-13 06:07 UTC, malinink commented
Мы должны возвращать сумму к досрочному полному погашению, где она будет?

2018-12-13 18:54 UTC, malinink approved these changes

2018-12-13 19:01 UTC, merged