Реализовать метод для удаления кредита
apmath-web/credit-kotlin pull request #19
Opened 2018-12-08 00:02 UTC by Meleorina

- [ ] Создать Action
- [ ] Добавить в Handler
- [ ] Реализовать метод delete
- [ ] Обработать ошибки
- [ ] Дополнить Issue при необходимости

2018-12-08 08:18 UTC, malinink requested changes

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/Handler.kt
> +            request.uri().matches(kotlin.text.Regex("credit/[0-9]*")) && request.method() == HttpMethod.DELETE
можно просто Regex писать, он понимает.

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/Handler.kt
> +        const val MESSAGE = "message"
верните табы!

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/credit/Delete.kt
> +        val id = request.uri().subSequence(7, request.uri().length).toString().toInt()
может быть его регуляркой забрать?

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/credit/Delete.kt
> +        val id = request.uri().subSequence(7, request.uri().length).toString().toInt()
Также id необходимо провалидировать, т.е. положительное число типа int.
Причем предлагаю сразу вынести в отдельный метод.

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/credit/Delete.kt
> +        return getResponse(HttpResponseStatus.OK)
не соответствует спецификации.

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/credit/Delete.kt
> +            throw Exception()
не согласен, тут не должно быть пустых ошибок.
также не ловите доменные исключения.

2018-12-08 08:18 UTC, malinink commented on src/main/kotlin/actions/Handler.kt
> +            -> return Create(repository).handle(request)
автоформатирование не всегда рулит, всегда смотрите diff перед добавлением файла к коммиту.
Я бы предложил оставить тут таб, т.к. более читабельно. Но можно похоливарить.

2018-12-14 20:31 UTC, Meleorina commented on src/main/kotlin/actions/credit/Delete.kt
> +        return getResponse(HttpResponseStatus.OK)
Там в разных местах по-разному написано... Написано респонс ОК и код 204, но код ОК - 200, а 204 - это no content

2018-12-27 18:36 UTC, malinink commented
@Meleorina оставшиеся замечания будут исправлены?

2018-12-31 12:04 UTC, malinink commented
@Meleorina все сделано от вас ничего не требуется.

2019-01-01 18:20 UTC, malinink approved these changes

2019-01-01 18:42 UTC, merged