Реализовать api метод для Осуществления платежа по кредиту
apmath-web/credit-kotlin pull request #22
Opened 2018-12-15 05:49 UTC by BarracudaPff

- [ ] Создать Action
- [ ] Добавить в Handler
- [ ] Решить проблему с immutable VO-Payment
- [ ] Сделать regular платежи
- [ ] Сделать early платежи
- [ ] Сделать перерасчет кредита
- [ ] Сделать конвертацию валюты
- [ ] Добавить новые exceptions при необходимости

2018-12-27 18:35 UTC, malinink commented
@BarracudaPff задачу то какую закрываем?

2018-12-27 18:46 UTC, BarracudaPff commented
Осуществление платежей же, фильтрацию я немного для себя сделал, ее все равно дописывать надо

2018-12-27 18:47 UTC, malinink commented
@BarracudaPff Дык, ссылку на задачу в PR добавьте!

2018-12-29 19:17 UTC, malinink requested changes
Предлагаю провести первый раунд исправлений, и потому уже проверить бизнесс логику.

По дате и валюте платежа, я бы хотел чтобы в случае, если они не переданы они наполнялись из кредита, т.е. пока что предложил бы сделать метод по возвращению даты след платежа, но в дальнейшем будем использовать получение next платежа из метода `getPayments`
Реализация прямо в экшене.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +        if (!validateRequest(request))
всегда используйте `{}`

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +    private val payment: Payment = Payment()
я бы предложил для большей наглядности использовать алиас, и явно указал бы название класса и переменной, `paymentViewModel`

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +            payment.payment!!,
Предлагаю использовать общий стиль, либо `!!` либо `as Type` у меня нет понимания как лучше в котлине, поэтому просьба поискать все за и против, и отписаться почему и на каком варианте остановились. 
Насколько я помню, `!!` не очень уважают и не сильно рекомендуют к использованию. (но контекст был другой!)

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +            payment.payment!!,
Ну и изменить в других методах соответственно.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/ListPayments.kt
> +            validation.addMessage(Message(
чем в 1 строку хуже? не широко было, и вполне читабельно.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/data/Money.kt
> +    operator fun plus(money: Money): Money {
не уверен что методы тут - хорошая идея, я бы использовал контейнер, и не замарачивался бы.
Также у меня есть соменения что я корректно использовал инлайн классы котлиновские, по моему первому разумению, тип должен был быть другим, но все операции должны были работать как надо. Чего не поиизошло. и постоянно обращаться к `.value` не очень удобно конечно. Предлагаю поисследовать.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/data/Money.kt
> +        return Money(value / money.value)
вы сделали money - псевдо immutable, а зачем?

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +    var remainAmount: Money = amount
модификатор доступа верните

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +            if (it.state == state && it.type == type || type == null)
дичайшее условие, сделайте реализацию пустой лучше уж. она не входила в текущую задачу.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +        return if (payment.date.dayOfMonth == agreementAt.dayOfMonth)
не согласен

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/valueObjects/Message.kt
> +data class Message(override val field: String, override val text: String) : MessageInterface
вот тут гораздо менее читабельно. чем вы руководствуетесь?

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/valueObjects/Validation.kt
> +    operator fun plus(validation: ValidationInterface): ValidationInterface {
добавили метод которого небыло в интерфейсе да еще и нигде не используете его, зачем?

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/valueObjects/payment/PaidPayment.kt
> +        p: PayPaymentInterface,
название не отражает содержимое переменной, именуйте правильно

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +            payment.currency!!,
может быть null, и тогда вы тут вывалитесь

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/actions/credit/payments/AddPayment.kt
> +            HttpResponseStatus.OK, JSONObject()
предложил бы отдельную переменную завести, и передать её уже потом в метод.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +        val type = getType(payment)
вообще не понял зачем делать метод, если можно просто взять тип? он у нас not null

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +            payment.type != type                -> throw WrongTypeException()
также не понял

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +            payment.currency != currency        -> throw WrongCurrencyException()
чтобы так сравнить, необходимо вначале проинициализировать в экшене это значение.

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +    private fun getPercentPayment(now: LocalDate): Double {
now  не очень информативно тут

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +            Money(body) > remainAmount                   -> throw PaymentMoreThanCreditAmontException()
проще лонги сравнивать, да и понятнее

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/viewModels/Payment.kt
> +        val raw = loadField(json, DATE, default = LocalDate.now().format(DateTimeFormatter.ISO_DATE)) ?: return true
по спецификации, дата платежа - это дата следующего платежа, поэтому было сотавлено значение null

2018-12-29 19:17 UTC, malinink commented on src/main/kotlin/domain/models/Credit.kt
> +        println(regularPayment)
что?

2019-02-09 10:16 UTC, closed without merging